export const data = {
  allData: [
    {
      title: "Antymon",
      symbol: "Sb",
      value: [3, 5],
      correct: null,
    },
    {
      title: "Arsen",
      symbol: "As",
      value: [3, 5],
      correct: null,
    },
    {
      title: "Azot",
      symbol: "N",
      value: [1, 2, 3, 4, 5],
      correct: null,
    },
    {
      title: "Bar",
      symbol: "Ba",
      value: [2],
      correct: null,
    },
    {
      title: "Bizmut",
      symbol: "Bi",
      value: [3, 5],
      correct: null,
    },
    {
      title: "Brom",
      symbol: "Br",
      value: [1, 3, 5, 7],
      correct: null,
    },
    {
      title: "Chlor",
      symbol: "Cl",
      value: [1, 3, 5, 7],
      correct: null,
    },
    {
      title: "Chrom",
      symbol: "Cr",
      value: [2, 3, 6],
      correct: null,
    },
    {
      title: "Cyna",
      symbol: "Sn",
      value: [2, 4],
      correct: null,
    },
    {
      title: "Cynk",
      symbol: "Zn",
      value: [2],
      correct: null,
    },
    {
      title: "Fosfor (biały)",
      symbol: "P",
      value: [3, 5],
      correct: null,
    },
    {
      title: "Glin",
      symbol: "Al",
      value: [3],
      correct: null,
    },
    {
      title: "Jod",
      symbol: "I",
      value: [1, 3, 5, 7],
      correct: null,
    },
    {
      title: "Krzem",
      symbol: "Si",
      value: [2, 4],
      correct: null,
    },
    {
      title: "Mangan",
      symbol: "Mn",
      value: [2, 3, 4, 6, 7],
      correct: null,
    },
    {
      title: "Maganez",
      symbol: "Mg",
      value: [2],
      correct: null,
    },
    {
      title: "Miedź",
      symbol: "Cu",
      value: [1, 2],
      correct: null,
    },
    {
      title: "Nikiel",
      symbol: "Ni",
      value: [2, 3],
      correct: null,
    },
    {
      title: "Ołów",
      symbol: "Pb",
      value: [2, 4],
      correct: null,
    },
    {
      title: "Potas",
      symbol: "K",
      value: [1],
      correct: null,
    },
    {
      title: "Rtęć",
      symbol: "Hg",
      value: [1, 2],
      correct: null,
    },
    {
      title: "Siarka",
      symbol: "S",
      value: [2, 4, 6],
      correct: null,
    },
    {
      title: "Sód",
      symbol: "Na",
      value: [1],
      correct: null,
    },
    {
      title: "Srebro",
      symbol: "Ag",
      value: [1, 2],
      correct: null,
    },
    {
      title: "Tlen",
      symbol: "O",
      value: [2],
      correct: null,
    },
    {
      title: "Wapń",
      symbol: "Ca",
      value: [2],
      correct: null,
    },
    {
      title: "Węgiel",
      symbol: "C",
      value: [2, 4],
      correct: null,
    },
    {
      title: "Wodór",
      symbol: "H",
      value: [1],
      correct: null,
    },
    {
      title: "Żelazo",
      symbol: "Fe",
      value: [2, 3],
      correct: null,
    },
  ],
};
